### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by Copperearth** [vikingmicrowave/Microwave-Open-Source#10]
It appears my XCode only wants to compile it into a .dylib instead of a .lib

**Comment by McSwaggens** [comment]
I hope you're joking...

**Comment by trinialol** [comment]
And you didn't even try to inject? :D 

Oh boy.

**Comment by Copperearth** [comment]
i am not joking
i have mac os 10.9.5 
doesnt even matter im gonna get ubuntu anyway

**Comment by trinialol** [comment]
lmao. 

Dude, dylib = lib..

just inject it with ./osxinj and have fun lol.

**Comment by dentmaged** [comment]
This hack doesn't work with Ubuntu. I recommend you to use AimTux on Ubuntu.

**Comment by bumbojumbo** [comment]
Aimtux is the best! Wish I knew how to get it on Macos.

**Comment by mxwll1** [comment]
If you need further help compiling https://mac.barbossa.pro/index.php?threads/how-to-compile-and-run.5/

**Comment by bumbojumbo** [comment]
Thanks looks good.
