### ISSUE TITLE
Injecting error

### ISSUE THREAD

**Issue by ghost** [vikingmicrowave/Microwave-Open-Source#11]
Whenever I try injecting the dylib into my game process I get this error 

> module: 0x78659D80
bootstrapfn: 0x37D00
pid: 10671
image name: /Users/Finn/Desktop/c++/osxinj/bootstrap.dylib
mach_inject: found threadEntry image at: 0x37000 with size: 9872
mach_inject failing.. (os/kern) invalid address

I've tried compiling and injecting as both i386 and x86_64 but I still get the same error
If anyone knows how I can fix this that's be great
 Cheers

**Comment by bumbojumbo** [comment]
Someone sent his precompiled folder jsut down load it, in terminal
CD downloads
CD Microwave-Open-Source
Sudo ./inject

**Comment by bumbojumbo** [comment]
https://jerr0w.xyz/dl/Microwave-Open-Source.zip

**Comment by ghost** [comment]
@bumbojumbo what's the difference between inject and osxinj?

**Comment by dentmaged** [comment]
I don't think there is any difference. It's just been renamed.

**Comment by bumbojumbo** [comment]
It's just less to write out in terminal.

**Comment by dentmaged** [comment]
@bumbojumbo It's the same length.

**Comment by bumbojumbo** [comment]
Are you retarded how is sudo ./inject the same as sudo ./osxinj csgo_osx64
libMicrowave.dylib

**Comment by trinialol** [comment]
> Are you retarded how is sudo ./inject the same as sudo ./osxinj csgo_osx64 libMicrowave.dylib

Nothing more to say.

**Comment by dentmaged** [comment]
@bumbojumbo You could just precode those values into osxinj.
