### ISSUE TITLE
No updates

### ISSUE THREAD

**Issue by aKalisch** [vikingmicrowave/Microwave-Open-Source#12]
Why there are no further updates anymore @vikingmicrowave

**Comment by bumbojumbo** [comment]
@aKalisch He seems to be inactive at the moment. No idea why.

**Comment by trinialol** [comment]
Just give him a bit time. Pretty sure he's working in the background already with the other contributors. This means that you can't see any progress here, because he didn't push anything new to this github.

But ofc he's not going to spend all his time into this project here. So patience is asked here.

**Comment by snyggen911** [comment]
There will be more updates, we are currently struggling with ImGui by hooking it. Offsets are pointing to wrong pointers but will fix it as soon as possible. Stay tuned!

Regards:
ViKiNG

**Comment by bumbojumbo** [comment]
Thanks!

**Comment by vikingmicrowave** [comment]
Official website of microwave:
https://mac.barbossa.pro/
Stay tuned for updates!

**Comment by bumbojumbo** [comment]
ETA?

**Comment by McSwaggens** [comment]
feel free to update it yourself...

**Comment by bumbojumbo** [comment]
Is the website just blank with some text so far?

**Comment by bumbojumbo** [comment]
What is the song on the website?

**Comment by vikingmicrowave** [comment]
@bumbojumbo Updates will be posted there.
Song, by KOLLEGAH

Regards: 
ViKiNG

**Comment by Noriaela** [comment]
@vikingmicrowave Amazing website tho 1 problem I signed up but the email confirm isnt sending and yes I made sure I put the email right

**Comment by bumbojumbo** [comment]
@sonicrules11 yeah I also found that was an issue but my account seems to
be working fine without confirming.

**Comment by vikingmicrowave** [comment]
Yesterday at 4:29 PM - ViKiNG: We currently have problem with mail server, thus makes us confirm you manually as a member.
