### ISSUE TITLE
Is this VAC detectable?

### ISSUE THREAD

**Issue by MyNameIsLebronJames** [vikingmicrowave/Microwave-Open-Source#13]
This wall hack for mac looks a bit different from the rest, so i'm wondering if this one is detected or not.

**Comment by bumbojumbo** [comment]
Are you retarded?

**Comment by MyNameIsLebronJames** [comment]
Uhm, I'm just asking?

**Comment by MyNameIsLebronJames** [comment]
So does anyone know if it's detectable?

**Comment by bumbojumbo** [comment]
No... It's not detected.

**Comment by Galenika** [comment]
Vac is shit. You should worry about Overwatch.
