### ISSUE TITLE
How do I turn team esp off?

### ISSUE THREAD

**Issue by MyNameIsLebronJames** [vikingmicrowave/Microwave-Open-Source#14]
How do I turn team esp off? I'm getting a bit lag whenever I play. Also, how do I get rid of the no recoil

**Comment by Acornay** [comment]
???

**Comment by bumbojumbo** [comment]
Comment a few lines out on paint traverse

**Comment by Acornay** [comment]
What?

**Comment by bumbojumbo** [comment]
If you don't know how to comment lines in xcode you don't deserve shit.

**Comment by Acornay** [comment]
okay? And you deserve it? You did the exact same thing, asking around how to do this how to do that.

**Comment by bumbojumbo** [comment]
I wasn't familiar with the injector. Just fuck off. There is better hacks
out now.

**Comment by Acornay** [comment]
And where? For all I know, there are only 2 of them. And this one is totally unique

**Comment by Acornay** [comment]
Can anyone help me?

**Comment by Noriaela** [comment]
@Acornay 
https://discord.gg/g2u3xXC join and go to pinned messages and close issue :)
