### ISSUE TITLE
Where did you learn how to do this? How do you do it?

### ISSUE THREAD

**Issue by NyxDaDev** [vikingmicrowave/Microwave-Open-Source#15]
Hey,
This is a nice project and I'd like to get started on my own. If you can direct me to any sources, please do. I prefer video tutorials. If there aren't can someone make one?

**Comment by drauf** [comment]
If you don't know C++, I'd start with learning that.
Then, just go to [YouTube](https://www.youtube.com/results?search_query=csgo+cheat+tutorial) if you prefer video tutorials. CS:GO is probably *the* game with the most cheating resources and open-source projects, you can easily find them just by googling. You'll need to learn some basic reverse-engineering and some Source SDK specific knowledge (e.g. how are the player entities stored in memory). Actually, there're so much materials that you probably won't have to reverse-engineer at all, you can find all the data you need on cheating forums.
