### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Noriaela** [vikingmicrowave/Microwave-Open-Source#2]
I found your UK Thread
http://www.unknowncheats.me/forum/counterstrike-global-offensive/204007-mac-os-microwave-1-0-0-a.html
I followed the tut but I get this
module: 0x0
dlopen error: dlopen(bootstrap.dylib, 6): image not found
pid: 14876
failed to inject: module:0x0 bootstrapfn:0x0

**Comment by sonicrules11** [comment]
nvm i'm an idiot

**Comment by sonicrules11** [comment]
I found your UK Thread
http://www.unknowncheats.me/forum/counterstrike-global-offensive/204007-mac-os-microwave-1-0-0-a.html
I followed the tut but I get this
module: 0x0
dlopen error: dlopen(bootstrap.dylib, 6): image not found
pid: 14876
failed to inject: module:0x0 bootstrapfn:0x0

**Comment by dentmaged** [comment]
I believe that's to do with the wrong architecture of bootstrap.dylib.

**EDIT**: It seems that bootstrap.dylib isn't actually given. You'll have to build it yourself using the code from here: https://github.com/scen/osxinj

I just compiled this, you can download it here: https://www.mediafire.com/?5t5vobhv9dfdam9.  Feel free to scan it on VirusTotal.

**Comment by Noriaela** [comment]
Ok either i'm a fucking idiot or i'm doing this wrong (i'm most likley a fucking idiot)
module: 0x0
dlopen error: dlopen(bootstrap.dylib, 6): no suitable image found.  Did find:
	bootstrap.dylib: mach-o, but wrong architecture
pid: 19577
failed to inject: module:0x0 bootstrapfn:0x0

**Comment by vikingmicrowave** [comment]
Hi sonicrules11!

It look's like you have wrong architecture. Try build it Universal x86_x64

**Comment by Noriaela** [comment]
[Is this supposed to look this way?](http://imgur.com/ZEyANs0)

**Comment by Galenika** [comment]
I get theese errors when trying to build bootstrap.
The errors remains when i also update to recommended settings.

<img width="258" alt="skarmavbild 2017-02-16 kl 15 59 04" src="https://cloud.githubusercontent.com/assets/19758031/23026276/0425a944-f461-11e6-86bf-8d3254a9c855.png">

**Comment by Noriaela** [comment]
I'm getting the same error when I try to build that. I wonder if its because of Yosemite

**Comment by Galenika** [comment]
I use Sierra.

**Comment by vikingmicrowave** [comment]
Hello @sonicrules11 and @makikg123 
try replace "__pthread_set_self" to "_pthread_set_self"

-Regards.

**Comment by Noriaela** [comment]
Ok I did that and its fixed 
Now when I open your Microwave.xcodeproj
i'm getting these errors 
![hmm](https://cloud.githubusercontent.com/assets/22671423/23042941/e18370be-f457-11e6-8e67-a93d95254e77.png)

**Comment by Noriaela** [comment]
It builds correctly but when I go to put 
/Users/jamesh/Desktop/Microwave-Open-Source-master/osxinj csgo_osx64 /Users/jamesh/Library/Developer/Xcode/DerivedData/Microwave-frhzndimfrlzbhfaxzqavatolama/Build/Products/Debug/libMicrowave.dylib
Because ./osxinj csgo_osx64 libMicrowave.lib doesnt work I get 
module: 0x0
dlopen error: dlopen(bootstrap.dylib, 6): image not found
pid: 26563
failed to inject: module:0x0 bootstrapfn:0x0
Do I put the boostrap file in a folder or something

**Comment by Noriaela** [comment]
haha fixed it I just did 
sudo -s
then went to the directory of the hack and i used
/Users/jamesh/Desktop/Microwave-Open-Source-master/osxinj csgo_osx64 /Users/jamesh/Library/Developer/Xcode/DerivedData/Microwave-frhzndimfrlzbhfaxzqavatolama/Build/Products/Debug/libMicrowave.dylib

**Comment by p0hjan** [comment]
i also get this error, but nothing works :s

**Comment by manigamer22** [comment]
So does this one work?
plz say yes

**Comment by dio346** [comment]
compiled and i get this

module: 0x0
dlopen error: dlopen(bootstrap.dylib, 6): no suitable image found.  Did find:
	bootstrap.dylib: mach-o, but wrong architecture
	/Users/dio/Downloads/Microwave-Open-Source-master/bootstrap.dylib: mach-o, but wrong architecture
pid: 5416
failed to inject: module:0x0 bootstrapfn:0x0

I tried building with all architecture (standard architecture, universal, 64 bit intel) but nothing works :(

**Comment by KuruKuru3532** [comment]
I'm a little late, but can someone put all the files onto Mediafire or something, cuz this is way to complex for my brain

**Comment by bumbojumbo** [comment]
If you still play csgo on mac theres something wrong with you. The game is
dead.

**Comment by Noriaela** [comment]
@PenguinsWillLickYou Try mine https://github.com/sonicrules11/Microwave-Open-Source it's a bit easier to compile but more a bit more steps
