### ISSUE TITLE
How good is this hack?

### ISSUE THREAD

**Issue by brendon11** [vikingmicrowave/Microwave-Open-Source#3]
For over a year, I Had to play Cs go on an iMac and was extremely frustrated do to the hacking scene on Mac OS X. I now, have a windows laptop, but I'm just curious how good with hack is I guess, don't really expect much since it's very new. But can it compete with other p2cs and perhaps any privates?

**Comment by brendon11** [comment]
How good this hack is i guess*

**Comment by McSwaggens** [comment]
It's just basic walls and visual recoil removal hack

**Comment by brendon11** [comment]
@McSwaggens ah, lol didn't look into code at all. We hopefully this develops more for the Mac users!

**Comment by Noriaela** [comment]
@brendon11 I've used it in a couple comp games and I will say its fun as hell to use it works well in faceit if you plan on using it for that but with faceit the walls are extremely terrible. If you plan on using this with faceit tho don't use it in tournaments

**Comment by vikingmicrowave** [comment]
I'm glad you liked it

**Comment by aKalisch** [comment]
Since this is internal, you can do whatever you want...

So it's as good as you customize it....

Already got Aimbot, Chams, RCS Crosshair and Bunnyhop working.

**Comment by Noriaela** [comment]
gj @aKalisch I was using the glow esp originally

**Comment by aKalisch** [comment]
@sonicrules11 I know ;-)
