### ISSUE TITLE
Suggestion: Config File

### ISSUE THREAD

**Issue by trinialol** [vikingmicrowave/Microwave-Open-Source#5]
Hello,

I just wanted to suggest a config-file for enabling/disabling:

- ESP (On/Off)
- ESP Team Only (On/Off)
- No visible Recoil (On/Off)

Would be awesome, if you could do that. :)

**Comment by vikingmicrowave** [comment]
@trinialol hmm, yeah. but all that comes along when ImGui is hooked.
