### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by p0hjan** [vikingmicrowave/Microwave-Open-Source#8]
Hi, ive previously used the glowhack previously which was not as complicated as this one. What exactly do you mean by "Compile"? Previously i have made a build ^With the glowhack, is that what im supposed to do? And if then how do i use the injector lol 
And switched as glowhack just crashes my game and makes my mouse spaz out so why not give this a try :P 
And what does "do " ./osxinj csgo_osx64 libMicrowave.lib "  Mean?

**Comment by p0hjan** [comment]
i made it into a dylib now, am i on the right tracks?

**Comment by p0hjan** [comment]
module: 0x0
dlopen error: dlopen(bootstrap.dylib, 6): image not found
pid: 3102
failed to inject: module:0x0 bootstrapfn:0x0

?

**Comment by p0hjan** [comment]
Okay, i managed to make the dylib, but i get the "image not found" error now, as posted over. How did everyone else fix this?:p

**Comment by aKalisch** [comment]
Get the bootstrap.dylib from the osxinj project on github

**Comment by p0hjan** [comment]
i tried that, but its empty? :S What do i do with the Bootstrap? xD And btw ur work in csgoGlow is <3 <3 But its way to bad atm :D

**Comment by p0hjan** [comment]
![skarmavbild 2017-02-24 kl 07 43 30](https://cloud.githubusercontent.com/assets/22863997/23293169/f8cc5c5a-fa64-11e6-8b6c-4e64803eaaf8.gif)

**Comment by p0hjan** [comment]
![skarmavbild 2017-02-24 kl 07 46 18](https://cloud.githubusercontent.com/assets/22863997/23293233/5e3ba6b8-fa65-11e6-9e43-e77bff21f515.gif)

Am i really that bad at this wtf..
And when i change it it says "Shouldnt it be __ "

**Comment by aKalisch** [comment]
rename __pthread_set_self with _pthread_set_self

**Comment by p0hjan** [comment]
Ah, it was at multiple spots. Thanks:)

**Comment by p0hjan** [comment]
Where do i put the bootstramp after this? @aKalisch

**Comment by aKalisch** [comment]
right beside the osxinj and the libmicrowave.dylib

**Comment by p0hjan** [comment]
@aKalisch ? xD

im sorry for n00b l33t skills bruh

**Comment by p0hjan** [comment]
but my question is, what am i now supposed to do with the bootstramp?

**Comment by aKalisch** [comment]
If you know how to you don't need to have all files in the same directory.

then you call them like `sudo /path/to/osxinj csgo_osx64 /another/path/to/the/libMicrowave.dylib`

**Comment by aKalisch** [comment]
You need the bootstrap.dylib to inject your hack into csgo.

**Comment by p0hjan** [comment]
Yes, but what do i do with the bootstrap now when i made it?

**Comment by p0hjan** [comment]
i have never been this confused my whole life @aKalisch 🖌

**Comment by aKalisch** [comment]
Really? I said that you need to put osxinj, bootstrap.dylib and the libMicrowave.dylib in the same folder.
Then call the command posted before in your Terminal... can't be that hard.
If it is you might should stop here and switch to an external hack for mac or stop cheating.

**Comment by p0hjan** [comment]
module: 0x0
dlopen error: dlopen(bootstrap.dylib, 6): image not found
pid: 3642
failed to inject: module:0x0 bootstrapfn:0x0 
Still same error, i did the exact commands (with my paths ofc)

**Comment by McSwaggens** [comment]
> image not found

Are you in the correct directory?

**Comment by p0hjan** [comment]
im 50% sure @McSwaggens i'll try to reinstall everything to fix it :P

**Comment by McSwaggens** [comment]
Just type `pwd` in the terminal to find out..

**Comment by p0hjan** [comment]
Yes, i am

**Comment by McSwaggens** [comment]
Make sure you're inside the directory, the command should look like:
```bash
sudo ./osxinj csgo_osx64 libMicrowave.dylib
```

**Comment by p0hjan** [comment]
Samuels-Air:~ samuelpohjantahti$ sudo /Users/samuelpohjantahti/Downloads/Microwave-Open-Source-master/osxinj csgo_osx64 /Users/samuelpohjantahti/Library/Developer/Xcode/DerivedData/Microwave-coxljkufxdjvaxguazikfzldcplb/Build/Products/Debug/libMicrowave.dylib 
/Users/samuelpohjantahti/Library/Developer/Xcode/DerivedData/Microwave-coxljkufxdjvaxguazikfzldcplb/Build/Products/Debug/libMicrowave.dylib
module: 0x0
dlopen error: dlopen(bootstrap.dylib, 6): image not found
pid: 3642
failed to inject: module:0x0 bootstrapfn:0x0

**Comment by p0hjan** [comment]
i made the bootstrap and everything, do i just have the bootstrap at the same spot as the osxinj? cuz i do, but i'll try again

**Comment by McSwaggens** [comment]
You're not inside of the `Microwave-Open-Source` directory...
```bash
cd Downloads/Microwave-Open-Source-master/
sudo ./osxinj csgo_osx64 libMicrowave.dylib
```

**Comment by p0hjan** [comment]
now i got wrong archtecture

**Comment by p0hjan** [comment]
module: 0x79E5A330
bootstrapfn: 0x248D00
pid: 3642
image name: /Users/samuelpohjantahti/Downloads/Microwave-Open-Source-master/bootstrap.dylib
mach_inject: found threadEntry image at: 0x248000 with size: 9904
mach_inject failing.. (os/kern) invalid address

**Comment by p0hjan** [comment]
Just keep on getting the invalid address whatever i do..

**Comment by p0hjan** [comment]
![skarmavbild 2017-02-24 kl 09 28 11](https://cloud.githubusercontent.com/assets/22863997/23296035/9c7305ee-fa73-11e6-8c4d-fa79bc71915e.gif)

**Comment by bumbojumbo** [comment]
On the gitter, someone sent the pre compiled files.

**Comment by p0hjan** [comment]
@bumbojumbo can you link?

**Comment by bumbojumbo** [comment]
https://gitter.im/Microwave-macOS/Lobby

**Comment by bumbojumbo** [comment]
https://www.unknowncheats.me/forum/downloads.php?do=file&title=Microwave%201.0.0&cid=156&ctitle=Counter%20Strike:%20Global%20Offensive&id=19219

**Comment by p0hjan** [comment]
hmm, something is wrong at my side. I still get the same error :p

**Comment by p0hjan** [comment]
Wait, no i fixed it. It should be working. but its not showing ingame now? xD @bumbojumbo

**Comment by p0hjan** [comment]
Samuels-Air:Microwave-Open-Source-master samuelpohjantahti$ sudo /Users/samuelpohjantahti/Downloads/Microwave-Open-Source-master/osxinj csgo_osx64 /Users/samuelpohjantahti/Downloads/Microwave-Open-Source-master/microwave.dylib 
/Users/samuelpohjantahti/Downloads/Microwave-Open-Source-master/microwave.dylib
module: 0x81D00000
bootstrapfn: 0x5FB1D30
pid: 5667
image name: /Users/samuelpohjantahti/Downloads/Microwave-Open-Source-master/bootstrap.dylib
mach_inject: found threadEntry image at: 0x105fb1000 with size: 10032
wrote param with size 80

**Comment by p0hjan** [comment]
ay its works, thanks

**Comment by bumbojumbo** [comment]
how did you get it to show in game?

**Comment by p0hjan** [comment]
well, type "cd /path/to/Microwavefolder" and then if u use the precompiled files (like me) just drag all the files into the folder, and then the sudo .osxinj csgo_osx64 microwave.dylib

**Comment by bumbojumbo** [comment]
Okay thanks hope that works

**Comment by bumbojumbo** [comment]
ayy it works!

**Comment by bumbojumbo** [comment]
It worked once, now nothing is showing up, when do I inject, in-game or on menu
